#define IOCTL_MAGIC_NUMBER 'z'
#define NUM_START 0x38

#define NUM_FOR_FUNC1 NUM_START
#define NUM_FOR_FUNC2 NUM_START+1
#define NUM_FOR_FUNC3 NUM_START+2

#define IOCTL_FUNC1 _IOWR(IOCTL_MAGIC_NUMBER, NUM_FOR_FUNC1, long)
#define IOCTL_FUNC2 _IOWR(IOCTL_MAGIC_NUMBER, NUM_FOR_FUNC2, long)
#define IOCTL_FUNC3 _IOWR(IOCTL_MAGIC_NUMBER, NUM_FOR_FUNC3, long)
